spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_db
    username: course
    password: pass
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/