spring:
  application:
    name: discovery-server
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
      enabled: false
    server:
      enable-self-preservation: false
      register-with-eureka: false
      fetch-registry: false
      enabled: false
    instance:
      prefer-ip-address: true

server:
  port: 8761