server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/trMuniz/ead-course-management-system
          search-paths: config-repo
          default-label: development