server:
    port: 8888

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.cloud: DEBUG

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/trMuniz/ead-course-management-system
          search-paths: config-repo
          default-label: development
  security:
    user:
      name: user
      password: password


