server:
  port: 8888

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.cloud: DEBUG

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/trMuniz/ead-course-management-system.git
          search-paths: config-repo
          default-label: development
          clone-on-start: true
        bootstrap: true
      enabled: true